In [1]:
import pandas as pd
import math
from table import *

In [2]:
df=pd.read_csv('weather-numerical.csv')
# sort by temperature
df=df.sort_values(by='temperature', ascending=True)
# df.head()
df

     outlook  temperature  humidity  windy play
6   overcast           64        65   True  yes
5      rainy           65        70   True   no
4      rainy           68        80  False  yes
8      sunny           69        70  False  yes
3      rainy           70        96  False  yes
13     rainy           71        91   True   no
7      sunny           72        95  False   no
11  overcast           72        90   True  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
1      sunny           80        90   True   no
12  overcast           81        75  False  yes
2   overcast           83        86  False  yes
0      sunny           85        85  False   no

In [4]:
medians=[]
# Median between every two consecutive values of temperature
for i in range(len(df)-1):
    medians.append((df.iloc[i]['temperature']+df.iloc[i+1]['temperature'])/2)

print('Median between every two consecutive values of temperature')
print(medians)

Median between every two consecutive values of temperature
[64.5, 66.5, 68.5, 69.5, 70.5, 71.5, 72.0, 73.5, 75.0, 77.5, 80.5, 82.0, 84.0]

In [5]:
less=[]
more=[]
gini=[]
minGini=math.inf
splitVal = 0

labels=[]
theTemps=[]

for i in medians:
    # Count all yes where temperature is less than and equal to median
    a=[df[df['temperature']<=i]['play'].value_counts().get('yes',0),df[df['temperature']<=i]['play'].value_counts().get('no',0)]
    less.append(a)
    # Count all no where temperature is less than and equal to median if not then 0
    b=[df[df['temperature']>i]['play'].value_counts().get('yes',0),df[df['temperature']>i]['play'].value_counts().get('no',0)]
    more.append(b)

    ans1=round(1-((a[0]/sum(a))**2+(a[1]/sum(a))**2),3)
    ans2=round(1-((b[0]/sum(b))**2+(b[1]/sum(b))**2),3)
    gini.append([ans1,ans2])

    temp=round((sum(a)/14)*ans1+(sum(b)/14)*ans2,3)
    theTemps.append(temp)

    # Find minimum gini index
    if temp<minGini:
        minGini=temp
        splitVal=i

    labels.append(str(i))

# print('Less than or equal to median')
# print(less)
# print('More than median')
# print(more)
# print('Gini index')
# print(gini)


t=make_table(
    rows=[less,more,gini,theTemps],
    labels=labels
)
print(t)

print('Minimum gini index')
print(minGini)
print('Split value')
print(splitVal)

┌──────────────┬──────────────┬────────────────┬───────────────┬───────────────┬────────────────┬────────────────┬────────────────┬─────────────┬─────────────┬────────────────┬──────────────┬──────────────┐
│ 64.5         │ 66.5         │ 68.5           │ 69.5          │ 70.5          │ 71.5           │ 72.0           │ 73.5           │ 75.0        │ 77.5        │ 80.5           │ 82.0         │ 84.0         │
├──────────────┼──────────────┼────────────────┼───────────────┼───────────────┼────────────────┼────────────────┼────────────────┼─────────────┼─────────────┼────────────────┼──────────────┼──────────────┤
│ [1, 0]       │ [1, 1]       │ [2, 1]         │ [3, 1]        │ [4, 1]        │ [4, 2]         │ [5, 3]         │ [5, 3]         │ [7, 3]      │ [7, 3]      │ [7, 4]         │ [8, 4]       │ [9, 4]       │
│ [8, 5]       │ [8, 4]       │ [7, 4]         │ [6, 4]        │ [5, 4]        │ [5, 3]         │ [4, 2]         │ [4, 2]         │ [2, 2]      │ [2, 2]      │ [2, 1]         │ [1, 1]       │ [0, 1]       │
│ [0.0, 0.473] │ [0.5, 0.444] │ [0.444, 0.463] │ [0.375, 0.48] │ [0.32, 0.494] │ [0.444, 0.469] │ [0.469, 0.444] │ [0.469, 0.444] │ [0.42, 0.5] │ [0.42, 0.5] │ [0.463, 0.444] │ [0.444, 0.5] │ [0.426, 0.0] │
│ 0.439        │ 0.452        │ 0.459          │ 0.45          │ 0.432         │ 0.458          │ 0.458          │ 0.458          │ 0.443       │ 0.443       │ 0.459          │ 0.452        │ 0.396        │
└──────────────┴──────────────┴────────────────┴───────────────┴───────────────┴────────────────┴────────────────┴────────────────┴─────────────┴─────────────┴────────────────┴──────────────┴──────────────┘

Minimum gini index
0.396
Split value
84.0

In [7]:
df=pd.read_csv('weather-numerical.csv')
# sort by temperature
df=df.sort_values(by='humidity', ascending=True)
df.head()

     outlook  temperature  humidity  windy play
6   overcast           64        65   True  yes
5      rainy           65        70   True   no
8      sunny           69        70  False  yes
10     sunny           75        70   True  yes
12  overcast           81        75  False  yes

In [ ]:
medians=[]
# Median between every two consecutive values of temperature
for i in range(len(df)-1):
    medians.append((df.iloc[i]['humidity']+df.iloc[i+1]['humidity'])/2)

print('Median between every two consecutive values of humidity')
print(medians)

In [10]:
less=[]
more=[]
gini=[]
minGini=math.inf
splitVal = 0

labels=[]
theTemps=[]

for i in medians:
    # Count all yes where temperature is less than and equal to median
    a=[df[df['humidity']<=i]['play'].value_counts().get('yes',0),df[df['humidity']<=i]['play'].value_counts().get('no',0)]
    less.append(a)
    # Count all no where temperature is less than and equal to median if not then 0
    b=[df[df['humidity']>i]['play'].value_counts().get('yes',0),df[df['humidity']>i]['play'].value_counts().get('no',0)]
    more.append(b)
    
    try:
        ans1=round(1-((a[0]/sum(a))**2+(a[1]/sum(a))**2),3)
    except:
        ans1=math.inf
    try:
        ans2=round(1-((b[0]/sum(b))**2+(b[1]/sum(b))**2),3)
    except:
        ans2=math.inf

    gini.append([ans1,ans2])

    temp=round((sum(a)/14)*ans1+(sum(b)/14)*ans2,3)
    theTemps.append(temp)

    # Find minimum gini index
    if temp<minGini:
        minGini=temp
        splitVal=i

    labels.append(str(i))

# print('Less than or equal to median')
# print(less)
# print('More than median')
# print(more)
# print('Gini index')
# print(gini)


t=make_table(
    rows=[less,more,gini,theTemps],
    labels=labels
)
print(t)

print('Minimum gini index')
print(minGini)
print('Split value')
print(splitVal)

┌──────────────┬──────────────┬──────────────┬──────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┬───────────────┐
│ 64.5         │ 66.5         │ 68.5         │ 69.5         │ 70.5          │ 71.5          │ 72.0          │ 73.5          │ 75.0          │ 77.5          │ 80.5          │ 82.0          │ 84.0          │
├──────────────┼──────────────┼──────────────┼──────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┼───────────────┤
│ [0, 0]       │ [1, 0]       │ [1, 0]       │ [1, 0]       │ [3, 1]        │ [3, 1]        │ [3, 1]        │ [3, 1]        │ [4, 1]        │ [4, 1]        │ [6, 1]        │ [6, 1]        │ [6, 1]        │
│ [9, 5]       │ [8, 5]       │ [8, 5]       │ [8, 5]       │ [6, 4]        │ [6, 4]        │ [6, 4]        │ [6, 4]        │ [5, 4]        │ [5, 4]        │ [3, 4]        │ [3, 4]        │ [3, 4]        │
│ [inf, 0.459] │ [0.0, 0.473] │ [0.0, 0.473] │ [0.0, 0.473] │ [0.375, 0.48] │ [0.375, 0.48] │ [0.375, 0.48] │ [0.375, 0.48] │ [0.32, 0.494] │ [0.32, 0.494] │ [0.245, 0.49] │ [0.245, 0.49] │ [0.245, 0.49] │
│ nan          │ 0.439        │ 0.439        │ 0.439        │ 0.45          │ 0.45          │ 0.45          │ 0.45          │ 0.432         │ 0.432         │ 0.368         │ 0.368         │ 0.368         │
└──────────────┴──────────────┴──────────────┴──────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────────┴───────────────┘

Minimum gini index
0.368
Split value
80.5